---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.8"

inputs:
- name: broker-src
  path: gopath/src/github.com/cloudfoundry-community/s3-broker
- name: broker-config

run:
  path: broker-config/tasks/test.sh
